import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "./components/navbar/navbar";
import { Footer } from "./components/footer/footer";
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import {Inter as FontSans} from "next/font/google";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "CarLink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"/>
      </head>
      <body
        className={cn("min-h-screen bg-background font-sans antialiased",fontSans.variable)}
      >
        <Navbar/>
        <NuqsAdapter>{children}</NuqsAdapter>
        <Footer/>
      </body>
    </html>
  );
}
